sudo: required
language: bash
services:
  - docker
before_script:
  - docker-compose build ex-generic-mock-server
script: 
  - docker-compose run --rm --entrypoint sh ex-generic-mock-server cd /code/ && composer install --no-interaction
  - docker-compose run --rm --entrypoint sh ex-generic-mock-server /code/vendor/bin/phpcs --standard=psr2 -n /code/src/
  - docker-compose run --rm --entrypoint sh ex-generic-mock-server /code/vendor/bin/phpcs --standard=psr2 -n /code/Tests/
  - docker-compose run --rm --entrypoint sh ex-generic-mock-server /code/vendor/bin/phpunit
after_success:
  - docker images
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true  
