sudo: required
language: bash
services:
  - docker
before_script:
  - docker-compose build ex-generic-mock-server
script: 
  - docker-compose run --rm --entrypoint sh ex-generic-mock-server /appcode/vendor/bin/phpcs --standard=psr2 -n /appcode/src/
  - docker-compose run --rm --entrypoint sh ex-generic-mock-server /appcode/vendor/bin/phpcs --standard=psr2 -n /appcode/Tests/
  - docker-compose run --rm --entrypoint sh ex-generic-mock-server /appcode/vendor/bin/phpunit
after_success:
  - docker images
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true  
